#!/usr/bin/env python3
"""
text2image.py

A production-ready CLI tool to generate images from text prompts using Hugging Face Diffusers.

Features:
- Configurable model, scheduler, guidance, steps, and output size
- GPU/CPU auto-selection and device-aware dtype handling
- Safe, authenticated model download using HUGGINGFACE_TOKEN or --hf-token
- Input validation, logging, and error handling
- Outputs saved to a timestamped file by default

Usage (example):
  HUGGINGFACE_TOKEN=your_token python text2image.py \
    --prompt "A futuristic city at sunset, cinematic, ultra-detailed" \
    --model "runwayml/stable-diffusion-v1-5" \
    --out "./out.png" --steps 30 --guidance 7.5 --height 512 --width 512

Author: Generated by an automated assistant
"""

from __future__ import annotations

import argparse
import datetime
import logging
import os
import sys
import uuid
from dataclasses import dataclass
from typing import Optional, Tuple

from PIL import Image
from tqdm import tqdm

import torch

try:
    # Diffusers import
    from diffusers import StableDiffusionPipeline
except Exception as e:  # pragma: no cover - graceful error for missing deps
    StableDiffusionPipeline = None  # type: ignore

# Configure module-level logger
LOG = logging.getLogger("text2image")
LOG.setLevel(logging.INFO)
handler = logging.StreamHandler(sys.stdout)
handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)s [%(name)s] %(message)s"))
LOG.addHandler(handler)


@dataclass
class GenerateConfig:
    prompt: str
    negative_prompt: Optional[str]
    model_id: str
    hf_token: Optional[str]
    out_path: str
    steps: int
    guidance_scale: float
    height: int
    width: int
    seed: Optional[int]
    device: str


def _validate_args(args: argparse.Namespace) -> GenerateConfig:
    """Validate CLI args and return GenerateConfig dataclass.

    Raises:
        ValueError: if any argument is invalid
    """
    prompt = args.prompt
    if not prompt or not prompt.strip():
        raise ValueError("--prompt must be a non-empty string")

    if args.steps <= 0 or args.steps > 200:
        raise ValueError("--steps must be > 0 and <= 200")

    if args.guidance < 0 or args.guidance > 50:
        raise ValueError("--guidance must be >= 0 and <= 50")

    if args.height % 8 != 0 or args.width % 8 != 0:
        raise ValueError("height and width must be divisible by 8 (model constraint)")

    hf_token = args.hf_token or os.environ.get("HUGGINGFACE_TOKEN") or os.environ.get("HF_TOKEN")
    if hf_token is None:
        LOG.warning("No HUGGINGFACE_TOKEN provided. Public models may still load if unauthenticated access is allowed.")

    device = "cuda" if torch.cuda.is_available() and not args.force_cpu else "cpu"

    # Build deterministic default output path if not provided
    out_path = args.out
    if not out_path:
        stamp = datetime.datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
        out_path = f"text2image_{stamp}_{uuid.uuid4().hex[:8]}.png"

    cfg = GenerateConfig(
        prompt=prompt,
        negative_prompt=args.negative_prompt,
        model_id=args.model,
        hf_token=hf_token,
        out_path=out_path,
        steps=args.steps,
        guidance_scale=args.guidance,
        height=args.height,
        width=args.width,
        seed=args.seed,
        device=device,
    )
    return cfg


def _get_pipeline(model_id: str, hf_token: Optional[str], device: str) -> StableDiffusionPipeline:
    """Load the Stable Diffusion pipeline with appropriate dtype and optimizations.

    Args:
        model_id: model repo id on Hugging Face
        hf_token: access token or None
        device: 'cuda' or 'cpu'

    Returns:
        StableDiffusionPipeline: ready-to-use pipeline moved to device

    Raises:
        RuntimeError: if diffusers is not installed or pipeline loading fails
    """
    if StableDiffusionPipeline is None:
        raise RuntimeError("diffusers package is not installed. Please install dependencies (see requirements.txt)")

    use_auth_token = hf_token

    # Choose dtype for performance/compatibility
    if device == "cuda":
        torch_dtype = torch.float16
    else:
        torch_dtype = torch.float32

    LOG.info("Loading model '%s' on device=%s with dtype=%s", model_id, device, torch_dtype)

    try:
        pipe = StableDiffusionPipeline.from_pretrained(
            model_id,
            revision=None,
            torch_dtype=torch_dtype,
            use_auth_token=use_auth_token,
        )
    except Exception as exc:  # pragma: no cover - handle runtime loading issues
        LOG.exception("Failed to load pipeline: %s", exc)
        raise RuntimeError(f"Failed to load model {model_id}: {exc}") from exc

    # Move to device
    try:
        pipe = pipe.to(device)
    except Exception:
        LOG.warning("Failed to move pipeline to device using .to(); falling back to per-component move")
        for name, comp in pipe.__dict__.items():
            try:
                if hasattr(comp, "to"):
                    pipe.__dict__[name] = comp.to(device)
            except Exception:
                pass

    # Enable memory efficient attention if available (xformers) for speed
    try:
        pipe.enable_xformers_memory_efficient_attention()
    except Exception:
        # Not fatal; optional performance improvement when available
        LOG.debug("xformers not available or failed to enable")

    return pipe


def generate_image(cfg: GenerateConfig) -> Tuple[Image.Image, dict]:
    """Generate an image from configuration.

    Returns tuple (PIL.Image, metadata)
    """
    pipe = _get_pipeline(cfg.model_id, cfg.hf_token, cfg.device)

    # Set deterministic seed for reproducibility if requested
    generator = None
    if cfg.seed is not None:
        generator = torch.Generator(device=cfg.device)
        generator.manual_seed(cfg.seed)

    # Diffusers pipeline expects height and width consistent with model
    LOG.info("Generating image (steps=%s, guidance=%s)", cfg.steps, cfg.guidance_scale)

    try:
        output = pipe(
            prompt=cfg.prompt,
            negative_prompt=cfg.negative_prompt,
            height=cfg.height,
            width=cfg.width,
            num_inference_steps=cfg.steps,
            guidance_scale=cfg.guidance_scale,
            generator=generator,
        )
    except Exception as exc:  # pragma: no cover - runtime generation errors
        LOG.exception("Failed during image generation: %s", exc)
        raise RuntimeError(f"Image generation failed: {exc}") from exc

    if not hasattr(output, "images") or len(output.images) == 0:
        raise RuntimeError("Pipeline returned no images")

    img = output.images[0]
    metadata = {
        "seed": cfg.seed,
        "prompt": cfg.prompt,
        "negative_prompt": cfg.negative_prompt,
        "model_id": cfg.model_id,
        "steps": cfg.steps,
        "guidance_scale": cfg.guidance_scale,
        "height": cfg.height,
        "width": cfg.width,
        "device": cfg.device,
    }

    return img, metadata


def save_image(img: Image.Image, out_path: str) -> None:
    """Save PIL image to out_path, creating directories as needed.

    Args:
        img: PIL Image to save
        out_path: destination file path (png or jpg)
    """
    os.makedirs(os.path.dirname(os.path.abspath(out_path)) or ".", exist_ok=True)
    try:
        img.save(out_path)
    except Exception as exc:
        LOG.exception("Failed to save image to %s: %s", out_path, exc)
        raise


def parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate images from text using Hugging Face Diffusers")
    parser.add_argument("--prompt", required=True, help="Text prompt describing the desired image")
    parser.add_argument("--negative-prompt", default=None, help="Negative prompt to avoid content")
    parser.add_argument("--model", default="runwayml/stable-diffusion-v1-5", help="Hugging Face model id (repo) to use")
    parser.add_argument("--hf-token", default=None, help="Hugging Face access token (overrides HUGGINGFACE_TOKEN env)")
    parser.add_argument("--out", default=None, help="Output file path (png/jpg). Default: timestamped file")
    parser.add_argument("--steps", type=int, default=30, help="Number of diffusion steps (1-200)")
    parser.add_argument("--guidance", type=float, default=7.5, help="Classifier-free guidance scale")
    parser.add_argument("--height", type=int, default=512, help="Output image height (multiple of 8)")
    parser.add_argument("--width", type=int, default=512, help="Output image width (multiple of 8)")
    parser.add_argument("--seed", type=int, default=None, help="Optional random seed for reproducibility")
    parser.add_argument("--force-cpu", action="store_true", help="Force CPU even if CUDA is available")
    parser.add_argument("--verbose", action="store_true", help="Verbose logging")
    return parser.parse_args(argv)


def main(argv: Optional[list[str]] = None) -> int:
    args = parse_args(argv)
    if args.verbose:
        LOG.setLevel(logging.DEBUG)

    try:
        cfg = _validate_args(args)
    except Exception as exc:
        LOG.error("Invalid arguments: %s", exc)
        return 2

    try:
        img, meta = generate_image(cfg)
    except Exception as exc:
        LOG.error("Generation failed: %s", exc)
        return 3

    try:
        save_image(img, cfg.out_path)
    except Exception as exc:
        LOG.error("Failed to save image: %s", exc)
        return 4

    LOG.info("Image saved to %s", cfg.out_path)
    LOG.debug("Generation metadata: %s", meta)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
