#!/usr/bin/env python3
"""
text2image.py

Command-line and programmatic interface to generate images from text prompts using
Hugging Face Diffusers (Stable Diffusion).

Features:
- Select device (cuda/auto/cpu) and dtype automatically for best performance
- Configurable inference parameters (guidance scale, steps, height/width)
- Deterministic generation using seeds
- Secure handling of Hugging Face token via env var HUGGINGFACE_TOKEN or CLI arg
- Robust input validation, logging, and error handling

Usage (CLI):
  python text2image.py --prompt "A painting of a futuristic city" --outdir ./outputs

This module is written with production considerations: explicit typing, logging,
resource cleanup, and clear error messages. It expects you to have accepted the
model license on Hugging Face for the chosen model and have a valid token if
required.

Author: Generated by assistant
"""

from __future__ import annotations

import argparse
import logging
import os
import sys
import time
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Generator as TypingGenerator, List, Optional, Tuple

import torch
from PIL.Image import Image

try:
    from diffusers import StableDiffusionPipeline
except Exception as exc:  # pragma: no cover - helpful error message when deps missing
    raise RuntimeError(
        "Failed to import diffusers. Ensure required packages are installed (see requirements.txt)."
    ) from exc


LOG = logging.getLogger(__name__)


def setup_logger(verbose: bool = False) -> None:
    """Configure root logger.

    Args:
        verbose: If True, set DEBUG level, else INFO.
    """
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(name)s - %(message)s",
        handlers=[logging.StreamHandler(sys.stdout)],
    )


@dataclass
class GenerationConfig:
    prompt: str
    negative_prompt: Optional[str]
    num_images: int
    height: int
    width: int
    num_inference_steps: int
    guidance_scale: float
    seed: Optional[int]
    device: str
    model_id: str
    token: Optional[str]
    output_dir: Path
    torch_dtype: Optional[str]


class Text2ImageGenerator:
    """Wrapper around a Stable Diffusion pipeline to generate images from text.

    This class hides device management, dtype selection, and provides a
    deterministic generation API.
    """

    def __init__(self, model_id: str, token: Optional[str], device: str = "auto", torch_dtype: Optional[str] = None) -> None:
        """Create and initialize the diffusion pipeline.

        Args:
            model_id: Hugging Face model id (e.g., "runwayml/stable-diffusion-v1-5").
            token: Hugging Face token or None to rely on cached credentials.
            device: 'auto', 'cuda', or 'cpu'. 'auto' will pick CUDA if available.
            torch_dtype: Optional dtype override ('fp16' or 'fp32'). If None, the
                implementation picks a sensible default depending on device.
        """
        LOG.debug("Initializing Text2ImageGenerator(model_id=%s, device=%s)", model_id, device)
        self.model_id = model_id
        self.token = token

        # Resolve device
        if device == "auto":
            self.device = "cuda" if torch.cuda.is_available() else "cpu"
        else:
            self.device = device

        # Dtype selection
        if torch_dtype is None:
            if self.device == "cuda":
                self.torch_dtype = torch.float16
            else:
                self.torch_dtype = torch.float32
        else:
            if torch_dtype.lower() == "fp16":
                self.torch_dtype = torch.float16
            elif torch_dtype.lower() in ("fp32", "float32"):
                self.torch_dtype = torch.float32
            else:
                raise ValueError("Unsupported torch_dtype value: %s" % torch_dtype)

        LOG.info("Loading model '%s' on device=%s dtype=%s", self.model_id, self.device, self.torch_dtype)

        try:
            # Use `from_pretrained` with dtype and token if provided.
            # For CUDA we typically benefit from fp16; for CPU use fp32.
            self.pipe = StableDiffusionPipeline.from_pretrained(
                self.model_id,
                revision=None,
                torch_dtype=self.torch_dtype,
                use_auth_token=self.token,
            )

            # Move to device
            self.pipe = self.pipe.to(self.device)

            # Performance: enable attention slicing if memory constrained
            try:
                self.pipe.enable_xformers_memory_efficient_attention()
                LOG.debug("Enabled xformers memory efficient attention (if available).")
            except Exception:
                LOG.debug("xformers not available or failed to enable; continuing without it.")

        except Exception as exc:  # pragma: no cover - runtime dependency/IO errors
            LOG.exception("Failed to load pipeline from model '%s'", self.model_id)
            raise

    def _get_generator(self, seed: Optional[int]) -> Optional[torch.Generator]:
        if seed is None:
            return None
        device_for_generator = "cpu" if self.device == "cpu" else self.device
        gen = torch.Generator(device_for_generator)
        gen.manual_seed(seed)
        return gen

    def generate(self, cfg: GenerationConfig) -> List[Image]:
        """Generate images for the given configuration.

        Args:
            cfg: GenerationConfig with prompt, steps, guidance, etc.

        Returns:
            A list of PIL Images.
        """
        if not cfg.prompt or not cfg.prompt.strip():
            raise ValueError("Prompt must be a non-empty string.")

        if cfg.num_images <= 0:
            raise ValueError("num_images must be > 0")

        if cfg.height % 8 != 0 or cfg.width % 8 != 0:
            raise ValueError("height and width must be multiples of 8 for most stable diffusion models.")

        LOG.debug("Starting generation: prompt=%s, images=%d, steps=%d", cfg.prompt, cfg.num_images, cfg.num_inference_steps)

        generator = self._get_generator(cfg.seed)

        # Use autocast when on cuda and using fp16
        use_autocast = (self.device != "cpu" and self.torch_dtype == torch.float16)

        images: List[Image] = []
        try:
            # The pipeline supports a batched num_images parameter in many versions.
            # We'll generate images in a loop to control naming and memory.
            for i in range(cfg.num_images):
                LOG.debug("Generating image %d/%d", i + 1, cfg.num_images)
                if use_autocast:
                    with torch.autocast(device_type=self.device):
                        out = self.pipe(
                            prompt=cfg.prompt,
                            negative_prompt=cfg.negative_prompt,
                            height=cfg.height,
                            width=cfg.width,
                            num_inference_steps=cfg.num_inference_steps,
                            guidance_scale=cfg.guidance_scale,
                            generator=generator,
                        )
                else:
                    out = self.pipe(
                        prompt=cfg.prompt,
                        negative_prompt=cfg.negative_prompt,
                        height=cfg.height,
                        width=cfg.width,
                        num_inference_steps=cfg.num_inference_steps,
                        guidance_scale=cfg.guidance_scale,
                        generator=generator,
                    )

                if hasattr(out, "images"):
                    img = out.images[0]
                elif isinstance(out, tuple) and len(out) > 0:
                    img = out[0][0]
                else:
                    raise RuntimeError("Unexpected output from pipeline: %s" % type(out))

                images.append(img)

        except RuntimeError as exc:  # pragma: no cover - runtime OOMs etc.
            LOG.exception("Runtime error during generation; this may be due to OOM. Error: %s", exc)
            raise

        LOG.info("Generated %d images", len(images))
        return images


def save_images(images: List[Image], outdir: Path, prefix: str = "gen") -> List[Path]:
    """Save list of PIL images to disk with unique filenames.

    Args:
        images: List of PIL Image objects
        outdir: Output directory
        prefix: Prefix for filename

    Returns:
        List of saved file paths
    """
    outdir.mkdir(parents=True, exist_ok=True)
    saved_paths: List[Path] = []
    timestamp = time.strftime("%Y%m%d-%H%M%S")
    for i, img in enumerate(images):
        unique = uuid.uuid4().hex[:8]
        filename = f"{prefix}-{timestamp}-{unique}-{i+1}.png"
        path = outdir / filename
        try:
            img.save(path)
            LOG.info("Saved image: %s", path)
            saved_paths.append(path)
        except Exception as exc:
            LOG.exception("Failed to save image to %s: %s", path, exc)
            raise
    return saved_paths


def parse_args(argv: Optional[List[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate images from text using Hugging Face Diffusers")
    parser.add_argument("--prompt", required=True, help="Text prompt describing the desired image")
    parser.add_argument("--negative-prompt", default=None, help="Negative prompt to discourage generation of undesired content")
    parser.add_argument("--outdir", default="outputs", help="Directory to write output images")
    parser.add_argument("--num-images", type=int, default=1, help="Number of images to generate (>=1)")
    parser.add_argument("--height", type=int, default=512, help="Output image height (multiple of 8)")
    parser.add_argument("--width", type=int, default=512, help="Output image width (multiple of 8)")
    parser.add_argument("--steps", type=int, default=30, help="Number of inference steps")
    parser.add_argument("--guidance-scale", type=float, default=7.5, help="Classifier-free guidance scale")
    parser.add_argument("--seed", type=int, default=None, help="Optional seed for deterministic output")
    parser.add_argument("--model", default="runwayml/stable-diffusion-v1-5", help="Hugging Face model id to use")
    parser.add_argument("--token", default=None, help="Hugging Face token; if omitted HUGGINGFACE_TOKEN env var is used")
    parser.add_argument("--device", default="auto", choices=["auto", "cpu", "cuda"], help="Compute device")
    parser.add_argument("--torch-dtype", default=None, choices=[None, "fp16", "fp32"], help="Optional dtype override")
    parser.add_argument("--verbose", action="store_true", help="Enable debug logging")
    return parser.parse_args(argv)


def main(argv: Optional[List[str]] = None) -> int:
    args = parse_args(argv)
    setup_logger(args.verbose)

    token = args.token or os.environ.get("HUGGINGFACE_TOKEN")
    if token is None:
        LOG.info("No HUGGINGFACE_TOKEN provided. If the model requires authentication, loading may fail.")

    try:
        outdir = Path(args.outdir)
        cfg = GenerationConfig(
            prompt=args.prompt,
            negative_prompt=args.negative_prompt,
            num_images=args.num_images,
            height=args.height,
            width=args.width,
            num_inference_steps=args.steps,
            guidance_scale=args.guidance_scale,
            seed=args.seed,
            device=args.device,
            model_id=args.model,
            token=token,
            output_dir=outdir,
            torch_dtype=args.torch_dtype,
        )

        # Input validation
        if cfg.num_images < 1 or cfg.num_images > 16:
            # Cap images per run to avoid resource exhaustion in casual usage
            LOG.warning("num_images should be between 1 and 16. Clamping value.")
            cfg.num_images = max(1, min(cfg.num_images, 16))

        if cfg.height <= 0 or cfg.width <= 0:
            raise ValueError("width and height must be positive integers")

        generator = Text2ImageGenerator(model_id=cfg.model_id, token=cfg.token, device=cfg.device, torch_dtype=cfg.torch_dtype)
        images = generator.generate(cfg)
        saved = save_images(images, cfg.output_dir, prefix="txt2img")
        LOG.info("All done. Saved %d images to %s", len(saved), cfg.output_dir)
        return 0

    except Exception as exc:  # pragma: no cover - top-level error handling
        LOG.exception("Failed to generate images: %s", exc)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
