#!/usr/bin/env python3
"""
text2image.py

A production-ready CLI utility to generate images from text prompts using Hugging Face Diffusers.

Features:
- Loads a Stable Diffusion style model from the Hugging Face Hub or a local path.
- Automatically picks optimal dtype (float16 on CUDA, float32 otherwise).
- Uses a modern scheduler (DPMSolverMultistep) for efficient sampling.
- Validates inputs and sanitizes output paths.
- Produces PNG output and a companion JSON metadata file containing generation parameters.
- Support for deterministic generation using a seed and batching (num_images_per_prompt).

Security & best practices:
- Requires HF token via environment variable (HF_TOKEN) for private models; token is not logged.
- Validates numeric parameters and prompt length.
- Avoids exposing secrets and limits file write locations.

Usage:
    python text2image.py --prompt "A scenic painting of mountains at sunrise" --out_dir ./outputs

Author: Generated by assistant
"""
from __future__ import annotations

import argparse
import json
import logging
import math
import os
import pathlib
import sys
import time
from dataclasses import asdict, dataclass
from datetime import datetime
from typing import Any, Dict, Optional

import numpy as np
import PIL.Image
import torch
from diffusers import DPMSolverMultistepScheduler, StableDiffusionPipeline
from diffusers.pipelines.stable_diffusion.safety_checker import StableDiffusionSafetyChecker

# Constants
DEFAULT_MODEL = "runwayml/stable-diffusion-v1-5"
MAX_PROMPT_LENGTH = 2000  # characters
ALLOWED_OUTPUT_ROOT = pathlib.Path(".").resolve()

# Logging config
logger = logging.getLogger("text2image")
handler = logging.StreamHandler(stream=sys.stdout)
formatter = logging.Formatter("%(asctime)s [%(levelname)s] %(message)s")
handler.setFormatter(formatter)
logger.addHandler(handler)
logger.setLevel(logging.INFO)


@dataclass
class GenerationConfig:
    prompt: str
    negative_prompt: Optional[str]
    model_id: str
    out_dir: str
    height: int
    width: int
    num_inference_steps: int
    guidance_scale: float
    num_images_per_prompt: int
    seed: Optional[int]
    device: str
    dtype: str
    auth_token: Optional[str]
    disable_safety_checker: bool


def _validate_and_normalize_args(args: argparse.Namespace) -> GenerationConfig:
    """Validate CLI args and return a GenerationConfig.

    Raises ValueError for invalid inputs.
    """
    if not args.prompt or not args.prompt.strip():
        raise ValueError("Prompt must be a non-empty string.")
    if len(args.prompt) > MAX_PROMPT_LENGTH:
        raise ValueError(f"Prompt exceeds max length of {MAX_PROMPT_LENGTH} characters.")

    # Ensure height and width are multiples of 8 (model constraint for many SD models)
    def _ceil_to_multiple(x: int, m: int) -> int:
        return int(math.ceil(x / m) * m)

    height = _ceil_to_multiple(args.height, 8)
    width = _ceil_to_multiple(args.width, 8)
    if height != args.height or width != args.width:
        logger.warning("Adjusted image size to nearest multiple of 8: %dx%d -> %dx%d",
                       args.height, args.width, height, width)

    if args.num_inference_steps <= 0 or args.num_inference_steps > 200:
        raise ValueError("num_inference_steps must be between 1 and 200")
    if args.guidance_scale < 1.0 or args.guidance_scale > 30.0:
        raise ValueError("guidance_scale should be in [1.0, 30.0]")
    if args.num_images_per_prompt <= 0 or args.num_images_per_prompt > 8:
        raise ValueError("num_images_per_prompt must be between 1 and 8 to avoid OOM")

    out_dir = pathlib.Path(args.out_dir).resolve()
    # Prevent writing outside repo area (simple guard) - configurable in production
    try:
        out_dir.relative_to(ALLOWED_OUTPUT_ROOT)
    except Exception:
        raise ValueError(f"out_dir must be within {ALLOWED_OUTPUT_ROOT}")

    out_dir.mkdir(parents=True, exist_ok=True)

    # Detect device
    device = args.device
    if device == "auto":
        device = "cuda" if torch.cuda.is_available() else "cpu"

    # dtype determination
    if device == "cuda":
        dtype = "float16"
    else:
        dtype = "float32"

    # Authentication token - prefer HF_TOKEN env var unless passed
    auth_token = args.hf_token or os.environ.get("HF_TOKEN")

    cfg = GenerationConfig(
        prompt=args.prompt,
        negative_prompt=args.negative_prompt,
        model_id=args.model_id,
        out_dir=str(out_dir),
        height=height,
        width=width,
        num_inference_steps=args.num_inference_steps,
        guidance_scale=args.guidance_scale,
        num_images_per_prompt=args.num_images_per_prompt,
        seed=args.seed,
        device=device,
        dtype=dtype,
        auth_token=auth_token,
        disable_safety_checker=args.disable_safety_checker,
    )
    return cfg


def _create_pipeline(model_id: str, device: str, dtype_str: str, auth_token: Optional[str], disable_safety_checker: bool) -> StableDiffusionPipeline:
    """Load and prepare the Stable Diffusion pipeline.

    Uses DPMSolverMultistepScheduler for improved sampling speed and quality.
    """
    torch_dtype = torch.float16 if dtype_str == "float16" else torch.float32

    logger.info("Loading model '%s' on device=%s dtype=%s", model_id, device, dtype_str)

    # Load pipeline
    try:
        pipe = StableDiffusionPipeline.from_pretrained(
            model_id,
            torch_dtype=torch_dtype,
            use_auth_token=auth_token,
        )
    except TypeError:
        # Some versions accept `token` instead of `use_auth_token`
        pipe = StableDiffusionPipeline.from_pretrained(
            model_id,
            torch_dtype=torch_dtype,
            token=auth_token,
        )

    # Replace scheduler with DPMSolverMultistep for better quality/speed
    try:
        scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
        pipe.scheduler = scheduler
    except Exception as e:
        logger.warning("Could not switch scheduler to DPMSolverMultistep: %s", e)

    if disable_safety_checker:
        logger.warning("Safety checker disabled. Be careful with generated content.")
        pipe.safety_checker = lambda images, clip_input: (images, [False] * len(images))  # type: ignore
    else:
        # Keep the default safety checker; if unavailable, warn but continue
        if not hasattr(pipe, "safety_checker") or pipe.safety_checker is None:
            logger.warning("No safety checker available for this pipeline; proceed with caution.")

    # Move to device
    pipe = pipe.to(device)

    # Enable attention slicing to reduce peak memory usage (helpful for lower VRAM GPUs)
    try:
        pipe.enable_attention_slicing()
    except Exception:
        pass

    return pipe


def _generate_images(pipe: StableDiffusionPipeline, cfg: GenerationConfig) -> Dict[str, Any]:
    """Generate images and return metadata including saved file names.

    Returns a dict with keys: 'outputs' -> list of file names, and metadata
    """
    generator = None
    if cfg.seed is not None:
        # RNG per image batch
        device = torch.device(cfg.device)
        gen = torch.Generator(device=device)
        gen.manual_seed(cfg.seed)
        generator = gen
        logger.info("Using deterministic seed: %d", cfg.seed)

    logger.info("Starting generation: prompt='%s' num_images=%d steps=%d guidance=%.2f size=%dx%d",
                (cfg.prompt if len(cfg.prompt) < 120 else cfg.prompt[:120] + "..."),
                cfg.num_images_per_prompt, cfg.num_inference_steps, cfg.guidance_scale, cfg.width, cfg.height)

    # The pipeline supports batched generation via num_images_per_prompt
    output_images = []
    start = time.time()

    try:
        result = pipe(
            prompt=cfg.prompt,
            negative_prompt=cfg.negative_prompt,
            height=cfg.height,
            width=cfg.width,
            num_inference_steps=cfg.num_inference_steps,
            guidance_scale=cfg.guidance_scale,
            num_images_per_prompt=cfg.num_images_per_prompt,
            generator=generator,
        )
    except Exception as e:
        logger.exception("Image generation failed: %s", e)
        raise

    # result.images is a list of PIL.Image
    images = result.images

    # Save images
    timestamp = datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
    saved_files = []
    for idx, img in enumerate(images):
        safe_prompt = ''.join(c for c in cfg.prompt if c.isalnum() or c in (' ', '-', '_'))
        safe_prompt = safe_prompt.strip().replace(' ', '_')[:128]
        filename = f"sd_{timestamp}_{idx}_{safe_prompt}.png"
        out_path = pathlib.Path(cfg.out_dir) / filename
        # Save as PNG with maximum quality
        img.save(str(out_path), format="PNG")
        saved_files.append(str(out_path))
        logger.info("Saved image: %s", out_path)

    end = time.time()
    metadata = {
        "model_id": cfg.model_id,
        "prompt": cfg.prompt,
        "negative_prompt": cfg.negative_prompt,
        "height": cfg.height,
        "width": cfg.width,
        "num_inference_steps": cfg.num_inference_steps,
        "guidance_scale": cfg.guidance_scale,
        "num_images": len(images),
        "duration_seconds": end - start,
        "device": cfg.device,
        "dtype": cfg.dtype,
        "seed": cfg.seed,
        "saved_files": saved_files,
        "timestamp_utc": timestamp,
    }

    # Save metadata
    meta_path = pathlib.Path(cfg.out_dir) / f"metadata_{timestamp}.json"
    with meta_path.open("w", encoding="utf-8") as fh:
        json.dump(metadata, fh, indent=2)
    logger.info("Saved metadata: %s", meta_path)

    return metadata


def _parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Text -> Image generation using Hugging Face Diffusers")
    p.add_argument("--prompt", type=str, required=True, help="Text prompt to condition the model")
    p.add_argument("--negative_prompt", type=str, default=None, help="Negative prompt to discourage content")
    p.add_argument("--model_id", type=str, default=DEFAULT_MODEL, help="Model id or local path to use")
    p.add_argument("--out_dir", type=str, default="./outputs", help="Directory to write outputs")
    p.add_argument("--height", type=int, default=512, help="Image height (must be multiple of 8)")
    p.add_argument("--width", type=int, default=512, help="Image width (must be multiple of 8)")
    p.add_argument("--num_inference_steps", type=int, default=30, help="Number of denoising steps")
    p.add_argument("--guidance_scale", type=float, default=7.5, help="Classifier-free guidance scale")
    p.add_argument("--num_images_per_prompt", type=int, default=1, help="How many images to generate per prompt")
    p.add_argument("--seed", type=int, default=None, help="Random seed for reproducibility")
    p.add_argument("--device", type=str, default="auto", choices=["auto", "cpu", "cuda"], help="Device to run on")
    p.add_argument("--hf_token", type=str, default=None, help="Hugging Face token (or set HF_TOKEN env var)")
    p.add_argument("--disable_safety_checker", action="store_true", help="Disable the built-in safety checker (use with caution)")
    p.add_argument("--verbose", action="store_true", help="Enable verbose logging")
    return p.parse_args(argv)


def main(argv: Optional[list[str]] = None) -> int:
    args = _parse_args(argv)
    if args.verbose:
        logger.setLevel(logging.DEBUG)

    try:
        cfg = _validate_and_normalize_args(args)
    except Exception as e:
        logger.error("Invalid arguments: %s", e)
        return 2

    # Load pipeline
    try:
        pipe = _create_pipeline(cfg.model_id, cfg.device, cfg.dtype, cfg.auth_token, cfg.disable_safety_checker)
    except Exception as e:
        logger.exception("Failed to create pipeline: %s", e)
        return 3

    # Generate
    try:
        metadata = _generate_images(pipe, cfg)
    except Exception as e:
        logger.exception("Generation error: %s", e)
        return 4

    logger.info("Generation completed successfully. Metadata: %s", json.dumps(metadata, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
